version: "3.5"

networks:
  devnet:
    name: ${NETWORK_NAME:?err}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 7.0.0.0/24

services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.nimiq.address=:8443
      - --entrypoints.rpc.address=:8648
      - --providers.docker=true
    ports:
      - "8443:8443"
      - "8648:8648"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      devnet:
        ipv4_address: 7.0.0.100

  seed1:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed1.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1.entrypoints=nimiq
      - traefik.http.routers.seed1.service=seed1
      - traefik.http.services.seed1.loadbalancer.server.port=8443

      # Accept outside RPC connections
      - traefik.http.routers.seed1-rpc.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1-rpc.entrypoints=rpc
      - traefik.http.routers.seed1-rpc.service=seed1-rpc
      - traefik.http.services.seed1-rpc.loadbalancer.server.port=8648
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.2/tcp/8443/ws
      - NIMIQ_HOST=seed1.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_PEER_KEY=fe3b33ed720a5d532e27551c3b9aa83d97a27e82c30d87fe1378936890f81ea6
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=f8ac8d3d52f72f86a97e83f6ccab9c8f60c70e92e13ea490ea3433b7611ab0058f0584d3e4a2b9856e482440967af01a6c878cb5ff0ea98acb07eec5fd0f5deb1db5fb2843d7bf34d7b9fddba5234943e6c3e491cbe08d071668affdf5d10000
      - RPC_ENABLED=true
      # - RPC_USERNAME=rpcclient
      # - RPC_PASSWORD=7F8E0E42-8ACF-47E7-8CC1-0EC66FA3D82D
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.2
    volumes:
      - "seed1:/home/nimiq/.nimiq:rw"

  seed2:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed2.rule=Host(`seed2.${NETWORK_NAME:?err}`)
    depends_on:
      - seed1
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.3/tcp/8443/ws
      - NIMIQ_HOST=seed2.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=bfbf1e23855190f03222bb2b19dc9d25843494d22bf8ccc1f7abfe6b3b185b3bf76537ee70e7ac5c7c6d7a0046e671bf610572e1cf89b407a7cd095ab9f0868da80003121a26d4d3be1e1abd10861f6c8601e94e0e448f4b86b7512764460100
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.3
    volumes:
      - "seed2:/home/nimiq/.nimiq:rw"

  seed3:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed3.rule=Host(`seed3.${NETWORK_NAME:?err}`)
    depends_on:
      - seed2
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.4/tcp/8443/ws
      - NIMIQ_HOST=seed3.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=eacdbf28aff34ca60f0b57c98d5b4bb32948710d4afa4b3567d21ef871845ada28bc6721b7720ce74242d45674cbc91e317c64f1109b547ef07d13f4e5e936ebd1e68a292f82c71dbb50f6ef68386b8066efa9e40aaa637f86922e90f73f0100
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.4
    volumes:
      - "seed3:/home/nimiq/.nimiq:rw"

  seed4:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed4.rule=Host(`seed4.${NETWORK_NAME:?err}`)
    depends_on:
      - seed3
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.5/tcp/8443/ws
      - NIMIQ_HOST=seed4.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=1aa577387bd1b63ee93dc2aa5547d6c3e78494ebffbbbecc6cdddf058d98c3be543b4454b6e3fe01a3c9d1e3ca35933d96727e29e47e48077488288b02bf8c0a3954ea20471723194a83099f9b434ad47fc67b3d44c61cca134ab9bc0df00000
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.5
    volumes:
      - "seed4:/home/nimiq/.nimiq:rw"

  seed5:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed5.rule=Host(`seed5.${NETWORK_NAME:?err}`)
    depends_on:
      - seed4
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.6/tcp/8443/ws
      - NIMIQ_HOST=see5.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=d7ad0b66cba9ed3e85b7ebc8f1630856c0e5bdbc916bcd4bf05ee9d1aaf36df2d3390b4f894d91a82c3e8fcb26c8d46b0bdc24118c6f7a62a52d8762795434d023c347035c3b19e6b40d0abd3069f882a94316c5cb2de4fad302571a74000100
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.6
    volumes:
      - "seed5:/home/nimiq/.nimiq:rw"

  seed6:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed6.rule=Host(`seed6.${NETWORK_NAME:?err}`)
    depends_on:
      - seed5
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.7/tcp/8443/ws
      - NIMIQ_HOST=seed6.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=adedffc0edd1b3f3c74155ef44eba23c1e9c1647442a0be4ae092913dcee84dc34d4ca78ce0b81d43c99e7752c317aaaef2c9186971e4f23348f4e9825acc635214f49551720aa76cbc661b552f771645bb8edc522c355c57a183e5c08290000
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.7
    volumes:
      - "seed6:/home/nimiq/.nimiq:rw"

  seed7:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed7.rule=Host(`seed7.${NETWORK_NAME:?err}`)
    depends_on:
      - seed6
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.8/tcp/8443/ws
      - NIMIQ_HOST=seed7.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=2114b52f5f49ae2e00ded9d2d6a65ae2b5e2ce24e128dc53bf4d20451fae883c9757f8957cf17e7c3b7e3f8f50b90ac16a973687383d093d2529b30ed15519e5d8e5aafb4c78e9dd24db2dd3a54761e8d6b540560aa04eda4350904301d50000
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.8
    volumes:
      - "seed7:/home/nimiq/.nimiq:rw"

  seed8:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed8.rule=Host(`seed8.${NETWORK_NAME:?err}`)
    depends_on:
      - seed6
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.9/tcp/8443/ws
      - NIMIQ_HOST=seed8.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      # - NIMIQ_PEER_KEY=3a55f2b5f7c66a4ce624c8189bb7d6217384ae67c4728591d5458beaab1b226a
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_NO_LMDB_SYNC=true
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_BLOCK_DELAY="0"
      - VALIDATOR_KEY=4f8dfc44cc94de6bae90d8281e783af7602b9308fc6770180c56d8507bc35ebb4340aabf2432aa78971099b1c30fec01f08f7f705429c106d370ea914b59da87a7a1badf91765de6e77c30ff4d5d0fc33f5c7c7d8645edeb18918bc6d7870000
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=debug
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.9
    volumes:
      - "seed8:/home/nimiq/.nimiq:rw"

volumes:
  seed1:
  seed2:
  seed3:
  seed4:
  seed5:
  seed6:
  seed7:
  seed8:
