[package]
name = "nimiq-rpc-interface"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.6"
thiserror = "1.0"
async-trait = "0.1"
hex = "0.4"
futures = "0.3"

beserial = { path = "../beserial" }
nimiq-hash = { path = "../hash", features = ["serde-derive"] }
nimiq-account = { path = "../primitives/account", features = ["serde-derive"] }
nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1", features = ["serde-derive"] }
nimiq-blockchain-albatross = { path = "../blockchain-albatross" }
nimiq-primitives = { path = "../primitives", features = ["coin", "account", "serde-derive"] }
nimiq-bls = { path = "../bls", features = ["serde-derive"] }
nimiq-keys = { path = "../keys", features = ["serde-derive"] }
nimiq-transaction = { path = "../primitives/transaction", features = ["serde-derive"] }
nimiq-collections = { path = "../collections", features = ["serde-derive", "bitset"] }
nimiq-vrf = { path = "../vrf", features = ["serde-derive"] }
nimiq-mempool = { path = "../mempool" }
nimiq-jsonrpc-core = { git = "https://github.com/nimiq/jsonrpc.git", branch = "sergio/tokio1.2" }
nimiq-jsonrpc-derive = { git = "https://github.com/nimiq/jsonrpc.git", optional = true, branch = "sergio/tokio1.2" }
nimiq-jsonrpc-client = { git = "https://github.com/nimiq/jsonrpc.git", optional = true, branch = "sergio/tokio1.2" }
nimiq-transaction-builder = { path = "../transaction-builder", features = ["serde-derive"] }

[features]
proxy = ["nimiq-jsonrpc-derive", "nimiq-jsonrpc-client"]
